package io.github.uharaqo.epoque.impl

import arrow.core.right
import io.github.uharaqo.epoque.api.CommandOutput
import io.github.uharaqo.epoque.api.EventWriter
import io.github.uharaqo.epoque.api.Version
import io.github.uharaqo.epoque.api.VersionedEvent
import io.github.uharaqo.epoque.impl.TestEnvironment.TestCommand.Create
import io.kotest.assertions.arrow.core.rethrow
import io.kotest.assertions.arrow.core.shouldBeRight
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.mockk.coEvery
import io.mockk.mockk
import io.mockk.slot

class CommandExecutorSpec : StringSpec(
  {
    "events generated by a command are written and returned properly" {
      // given
      val eventWriter = mockk<EventWriter>()
      val slot = slot<List<VersionedEvent>>()
      coEvery { eventWriter.write(any(), capture(slot), any()) } returns Unit.right()

      val dummyCommandExecutor = dummyCommandExecutor(eventWriter = eventWriter)

      // when
      val out = dummyCommandExecutor.execute(dummyJournalKey.id, Create("Whatever"))

      // then: returned == written
      out shouldBeRight CommandOutput(slot.captured)

      // then
      out.rethrow().events shouldBe listOf(
        VersionedEvent(Version(3), resourceCreatedEventType, serializedEvent1),
        VersionedEvent(Version(4), resourceCreatedEventType, serializedEvent2),
      )
    }
  },
) {
  companion object : TestEnvironment() {
    fun dummyCommandExecutor(eventWriter: EventWriter) =
      CommandExecutor(
        dummyJournalKey.groupId,
        dummyCommandHandler,
        dummyEventCodecRegistry,
        dummyEventHandlerExecutor,
        dummyEventLoader,
        eventWriter,
        dummyTransactionStarter,
      )
  }
}
